# Generated by Django 6.0.6 on 2026-06-21 23:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                (
                    'cycle_start_date',
                    models.DateField(
                        blank=True,
                        help_text='Cycle start date for "2 on, 2 off" / "3 on, 2 off" rules.',
                        null=True,
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'ordering': ['last_name', 'first_name', 'nickname'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    'location_type',
                    models.CharField(
                        choices=[('STORE', 'Store'), ('CASH_REGISTER', 'Cash register')],
                        default='STORE',
                        max_length=20,
                    ),
                ),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchedulePeriod',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('year', models.PositiveIntegerField(unique=True)),
                (
                    'start_date',
                    models.DateField(help_text='Monday of the first week of the current schedule.'),
                ),
                (
                    'end_date',
                    models.DateField(help_text='Last day of the current schedule (5 weeks).'),
                ),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'schedule period',
                'verbose_name_plural': 'schedule periods',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleShift',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'schedule shift',
                'verbose_name_plural': 'schedule shifts',
                'ordering': ['date', 'location__sort_order', 'location__name'],
            },
        ),
        migrations.CreateModel(
            name='WorkRule',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    'code',
                    models.CharField(
                        choices=[
                            ('WORK_2_ON_2', '2 days on, 2 days off'),
                            ('WORK_3_ON_2', '3 days on, 2 days off'),
                            ('MAX_2_CONSECUTIVE', 'No more than 2 consecutive days'),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                ('name', models.CharField(max_length=120)),
                (
                    'kind',
                    models.CharField(
                        choices=[('CYCLE', 'Shift cycle'), ('CONSTRAINT', 'Constraint')],
                        max_length=20,
                    ),
                ),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'work rule',
                'verbose_name_plural': 'work rules',
                'ordering': ['code'],
            },
        ),
    ]
