# Generated by Django 6.0.6 on 2026-06-21 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='employee_profile',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='locations',
            field=models.ManyToManyField(
                blank=True, related_name='employees', to='schedules.location'
            ),
        ),
        migrations.AddField(
            model_name='scheduleshift',
            name='employee',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='shifts',
                to='schedules.employee',
            ),
        ),
        migrations.AddField(
            model_name='scheduleshift',
            name='location',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='shifts',
                to='schedules.location',
            ),
        ),
        migrations.AddField(
            model_name='scheduleshift',
            name='period',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='shifts',
                to='schedules.scheduleperiod',
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_rules',
            field=models.ManyToManyField(
                blank=True, related_name='employees', to='schedules.workrule'
            ),
        ),
        migrations.AddConstraint(
            model_name='scheduleshift',
            constraint=models.UniqueConstraint(
                fields=('date', 'location'), name='unique_shift_per_location_day'
            ),
        ),
    ]
